# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# build with latest available ubuntu version
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_install:
      - pip install --find-links=https://girder.github.io/large_image_wheels --no-cache GDAL
    # patch deprecated and sphinx version to mimic nox build
    post_install:
      - pip install git+https://github.com/jenshnielsen/sphinx.git@fix_9884
      - pip install git+https://github.com/12rambau/deprecated.git@master
    pre_build:
      - sphinx-apidoc --force --module-first --templatedir=docs/source/_templates/apidoc -o docs/source/modules ./sepal_ui

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
