from configparser import ConfigParser
from pathlib import Path

config_file = Path.home() / ".sepal-ui-config"
config = ConfigParser()
"ConfigParser: the configuration object generated by sepal-ui based application to save parameters such as language or theme"
config.read(config_file)
