FROM mambaorg/micromamba:latest

WORKDIR /usr/local/lib/{{project_slug}}

USER root
RUN apt-get update && apt-get install -y \
    nano curl neovim supervisor netcat-openbsd net-tools git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /tmp/* \
    && rm -rf /var/tmp/*

COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf

USER $MAMBA_USER
COPY . /usr/local/lib/{{project_slug}}
RUN micromamba create -n {{conda_env_name}} python=3.12 pip -c conda-forge -y && \
    micromamba run -n {{conda_env_name}} pip install -e . --no-cache-dir && \
    micromamba clean --all --yes && \
    rm -rf ~/.cache/pip

EXPOSE {{container_port}}

USER root
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
